# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.TextField(blank=True, max_length=500, null=True, verbose_name='picture URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='TempProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('invitation_code', models.TextField(blank=True, max_length=50, null=True, verbose_name='invitation code')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='created at')),
                ('activated_at', models.DateField(blank=True, default=None, null=True, verbose_name='activated at')),
                ('is_pending', models.BooleanField(default=True, verbose_name='is pending')),
            ],
            options={
                'ordering': ('email',),
            },
        ),
    ]
