# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='ask_reset_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_token',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='update_token_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
