# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
        migrations.AddField(
            model_name='invitation',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='first_name',
            field=models.TextField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='last_name',
            field=models.TextField(default='--', max_length=200),
        ),
    ]
