# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20170606_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sender_verified',
            field=models.BooleanField(default=True),
        ),
    ]
