# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_invitation_sender_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='first_name',
            new_name='receiver_first_name',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='last_name',
            new_name='receiver_last_name',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='email',
        ),
        migrations.AddField(
            model_name='invitation',
            name='receiver_email',
            field=models.EmailField(default='', max_length=254, verbose_name='receiver email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender_email',
            field=models.EmailField(default='', max_length=254, verbose_name='sender email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender_first_name',
            field=models.TextField(default='--', max_length=200),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender_last_name',
            field=models.TextField(default='--', max_length=200),
        ),
    ]
