# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170607_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message_text',
            field=models.TextField(max_length=500, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='receiver_email',
            field=models.EmailField(max_length=254, verbose_name='Receiver email address'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='receiver_first_name',
            field=models.TextField(default='--', max_length=200, verbose_name='Receiver first name'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='receiver_last_name',
            field=models.TextField(default='--', max_length=200, verbose_name='Receiver last name'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sender_email',
            field=models.EmailField(max_length=254, verbose_name='Sender email address'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sender_first_name',
            field=models.TextField(default='--', max_length=200, verbose_name='Sender first name'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sender_last_name',
            field=models.TextField(default='--', max_length=200, verbose_name='Sender last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture_url',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Picture URL'),
        ),
    ]
