# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20170712_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth Date'),
        ),
    ]
