# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20170821_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(related_name='profile_tags', to='dashboard.Tag'),
        ),
    ]
