# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20170830_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOfInnovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='sourceOfInnovation',
            field=models.ManyToManyField(related_name='profile_source_of_innovation', to='dashboard.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='typesOfInnovation',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Types of Innovation'),
        ),
    ]
