# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170830_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sourceOfInnovation',
            new_name='source_of_innovation',
        ),
    ]
