# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20170830_0938'),
        ('dashboard', '0023_auto_20170830_1008'),
    ]

    operations = [
    ]
