# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20170830_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='statement',
            field=models.TextField(blank=True, null=True, verbose_name='Statement'),
        ),
    ]
