# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_profile_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Place'),
        ),
    ]
