# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_profile_statement'),
        ('dashboard', '0024_merge_20170830_1330'),
    ]

    operations = [
    ]
