# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_merge_20170830_1456'),
        ('dashboard', '0025_profile_place'),
    ]

    operations = [
    ]
