# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_merge_20170913_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='technical_expertise',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Technical Expertise'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='socialLinks',
            field=models.TextField(blank=True, default='[{"name":"twitter","link":""},{"name":"google-plus","link":""},{"name":"facebook","link":""}]', max_length=200, null=True, verbose_name='Social Links'),
        ),
    ]
