# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20171127_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role_other',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Role other'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sector_other',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Sector other'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='technical_expertise_other',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Technical Expertise other'),
        ),
    ]
