# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20171127_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latlng', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('country_short', models.CharField(blank=True, max_length=200, null=True)),
                ('post_code', models.CharField(blank=True, max_length=200, null=True)),
                ('city_alias', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('city', 'latlng'),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ManyToManyField(related_name='profile_location', to='dashboard.Location'),
        ),
    ]
