# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20171205_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('city', 'lat', 'lng')},
        ),
        migrations.RemoveField(
            model_name='location',
            name='latlng',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
