# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-06 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20171205_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('lat', 'lng', 'city')},
        ),
        migrations.AlterField(
            model_name='location',
            name='city_alias',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
