# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-06 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20171206_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
