# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0037_auto_20171206_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_picture', models.ImageField(blank=True, null=True, upload_to='images/challenge', verbose_name='Challenge picture')),
                ('title', models.TextField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('video_link', models.TextField(blank=True, max_length=200, null=True, verbose_name='Video link')),
                ('coordinator_email', models.EmailField(max_length=254, verbose_name='Coordinator email address')),
                ('les', models.IntegerField(choices=[(0, 'Spain'), (1, 'Italy'), (2, 'Slovakia'), (3, 'United Kingdom')], default=0)),
                ('tags', models.ManyToManyField(related_name='challenge_tags', to='dashboard.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_picture', models.ImageField(blank=True, null=True, upload_to='images/challenge', verbose_name='Company picture')),
                ('name', models.TextField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('tags', models.ManyToManyField(related_name='company_tags', to='dashboard.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_interest', to='dashboard.Profile')),
            ],
        ),
    ]
