# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_challenge_company_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='video_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video link'),
        ),
    ]
