# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-05 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20180205_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 5, 14, 34, 15, 23784)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 5, 14, 34, 19, 735837)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_picture',
            field=models.ImageField(default=1, upload_to='images/challenge', verbose_name='Challenge picture'),
            preserve_default=False,
        ),
    ]
