# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-06 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20180205_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_picture',
            new_name='logo',
        ),
    ]
