# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-07 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20180206_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
