# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20180207_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='restricted_to',
            field=models.CharField(default=False, max_length=100, verbose_name='Restricted to'),
        ),
    ]
