# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_challenge_restricted_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='restricted_to',
            field=models.CharField(blank=True, max_length=100, verbose_name='Restricted to'),
        ),
    ]
