# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-14 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20180213_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('picture', models.ImageField(upload_to='images/challenge', verbose_name='Challenge picture')),
                ('details', models.TextField(verbose_name='Details')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('project_url', models.CharField(max_length=50, verbose_name='Title')),
                ('contributors', models.ManyToManyField(related_name='contributors', to='dashboard.Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
                ('tags', models.ManyToManyField(related_name='tags', to='dashboard.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='restricted_to',
            field=models.CharField(blank=True, max_length=100, verbose_name='Restricted to area of'),
        ),
    ]
