# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-15 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20180214_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crm_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
