# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_profile_crm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='details',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
    ]
