# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20180220_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator_role',
            field=models.TextField(blank=True, null=True, verbose_name='Creator Role'),
        ),
    ]
