# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20180228_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
