# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_remove_project_contributors'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.IntegerField(default=0)),
                ('type', models.CharField(default='article', max_length=50, verbose_name='Type')),
            ],
        ),
    ]
