# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityproxy',
            name='type',
            field=models.CharField(default='news', max_length=50, verbose_name='Type'),
        ),
    ]
