# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-19 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20180418_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entityproxy',
            unique_together=set([('externalId', 'type')]),
        ),
    ]
