# Generated by Django 2.0.5 on 2018-05-19 08:52

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_auto_20180517_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='place',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
