# Generated by Django 2.0.5 on 2018-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_auto_20180523_1031'),
    ]

    operations = [

    ]
