# Generated by Django 2.0.5 on 2018-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_profile_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
