# Generated by Django 2.0.5 on 2018-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_tag_type'),
    ]
    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
