# Generated by Django 2.0.5 on 2018-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20180928_1422'),
    ]

    operations = [

    ]
