# Generated by Django 2.0.5 on 2018-07-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20180719_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
