# Generated by Django 2.0.5 on 2018-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_auto_20180719_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activities_area',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='activities_domain',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='activities_skills',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='activities_technology',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
