# Generated by Django 2.0.5 on 2018-10-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_auto_20180928_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latlong',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
