# Generated by Django 2.0.5 on 2018-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_auto_20180928_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='domain',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='technology',
            field=models.TextField(blank=True),
        ),
    ]
