# Generated by Django 2.0.5 on 2018-10-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20180928_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='technology',
        ),
    ]
