# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import pss.models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0002_auto_20170804_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='zip_location',
            field=models.FileField(upload_to=pss.models.upload_to_and_rename, verbose_name='Zip Location'),
        ),
    ]
