# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20170718_1044'),
        ('pss', '0003_auto_20170804_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='profile',
        ),
        migrations.AddField(
            model_name='application',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile'),
            preserve_default=False,
        ),
    ]
