# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0004_auto_20170804_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='les',
            field=models.IntegerField(choices=[(0, 'Spain'), (1, 'Italy'), (2, 'Slovakia'), (3, 'United Kingdom')], default=0),
        ),
    ]
