# Generated by Django 2.0.5 on 2018-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterprofile',
            name='user_id',
            field=models.CharField(default='-1', max_length=200),
        ),
    ]
