# Generated by Django 2.0.5 on 2018-07-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_twitterprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterprofile',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile'),
        ),
    ]
