# Generated by Django 2.0.5 on 2018-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20180719_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterprofile',
            name='screen_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
