# Generated by Django 2.0.5 on 2018-07-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_twitterprofile_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterprofile',
            name='screen_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
