# Generated by Django 2.0.5 on 2018-10-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20180731_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterprofile',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitterauth', to='dashboard.Profile'),
        ),
    ]
